---
title: "Note in the Pocket Exploratory Data Analysis Report"
author: Alvin Sheng, Jimmy Hickey, Naomi Giertych, Yinqiao Wang, Jake Koerner, Hyoshin Kim
site: bookdown::bookdown_site
delete_merged_file: true
output:
  bookdown::pdf_document2:
    toc: yes
    toc_depth: 2
abstract: |
  This report contains an exploratory data analysis of the requests filled by Note in the Pocket from 2019 to the present.
---

\newpage

```{r child = 'EDA/item_plots_agg.Rmd'}
```

\newpage

```{r child = 'EDA/request_lag.Rmd'}
```

\newpage

```{r child = 'EDA/EDA for the categorical variables.Rmd'}
```

\newpage

```{r child = 'EDA/EDA_character_sizegender.Rmd'}
```

\newpage

# Forecasting Future Donations and Requests

```{r, echo = F}
dat <- matrix(c(41,   50,
                28,   49,
                40,   58,
                38,   60,
                60,   55,
                99,   18,
                91,   17,
                45,   60,
                61,   61,
                55,   46,
                53,   66,
                16,   38),
              nrow = 12, ncol = 2, byrow = T)

load(here("zoho_forecasting/boys_tops10_np.RData"))

post_median_counts <- apply(boys_tops10_np$post_pred, c(2, 3), median)

post_quantile2.5_counts <- apply(boys_tops10_np$post_pred, c(2, 3), function(vec) quantile(vec, c(.025)))
post_quantile97.5_counts <- apply(boys_tops10_np$post_pred, c(2, 3), function(vec) quantile(vec, c(.975)))

matplot(dat, type = "l", col = 1, lwd = 2, ylim = c(-5, 150), 
        xlab = "Weeks Since Jan 9", ylab = "Count", 
        main = "Observed and warpDLM Forecasted Counts, BOY-TOP-10")

abline(h = 0, col = 2)

matplot(post_median_counts, type = "l", col = 3, add = T, lwd = 2)

matplot(post_quantile2.5_counts, type = "l", col = 3, add = T, lwd = 1)

matplot(post_quantile97.5_counts, type = "l", col = 3, add = T, lwd = 1)

legend("topleft", legend = c("Observed Donated", "Observed Distributed", 
                             "warpDLM Donated", "warpDLM Distributed", "Corresponding 95% Credible Intervals"), 
       col = c(1, 1, 3, 3, 3), lty = c(1, 2, 1, 2, 1), lwd = c(2, 2, 2, 2, 1))
```



