---
title: "Example Zoho Report Using warpDLM Results"
author: "Alvin Sheng"
date: "4/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, error=FALSE, message=FALSE)
library(tidyverse)
library(ggpubr)
library(here)
```

<!-- read in corresp. warpDLM objects -->

```{r}
dat <- matrix(c(41,   50,
                28,   49,
                40,   58,
                38,   60,
                60,   55,
                99,   18,
                91,   17,
                45,   60,
                61,   61,
                55,   46,
                53,   66,
                16,   38),
              nrow = 12, ncol = 2, byrow = T)

load(here("zoho_forecasting/boys_tops10_np.RData"))

```


```{r}

post_median_counts <- apply(boys_tops10_np$post_pred, c(2, 3), median)

post_quantile2.5_counts <- apply(boys_tops10_np$post_pred, c(2, 3), function(vec) quantile(vec, c(.025)))
post_quantile97.5_counts <- apply(boys_tops10_np$post_pred, c(2, 3), function(vec) quantile(vec, c(.975)))

matplot(dat, type = "l", col = 1, lwd = 2, ylim = c(-5, 150), 
        xlab = "Weeks Since Jan 9", ylab = "Count", 
        main = "Observed and warpDLM Forecasted Counts, BOY-TOP-10")

abline(h = 0, col = 2)

matplot(post_median_counts, type = "l", col = 3, add = T, lwd = 2)

matplot(post_quantile2.5_counts, type = "l", col = 3, add = T, lwd = 1)

matplot(post_quantile97.5_counts, type = "l", col = 3, add = T, lwd = 1)

legend("topleft", legend = c("Observed Donated", "Observed Distributed", 
                             "warpDLM Donated", "warpDLM Distributed", "Corresponding 95% Credible Intervals"), 
       col = c(1, 1, 3, 3, 3), lty = c(1, 2, 1, 2, 1), lwd = c(2, 2, 2, 2, 1))
```



```{r}

# TODO: apply particle filtering on the boys_tops10_np.RData. 
# may need to study paper a bit more on this

# TODO: apply the plan of combining requests side and donations side curves

# TODO: Ask Steve Deal for extra April data, just before setting it up at Note in the Pocket.

# TODO: Idea: perhaps at beginning, with so little data, focus on requests side of the process. Can use orders filled data for this. Just say, take the donations side with grain of salt in the beginning

```




